/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package resto.gui;








/**
 *
 * @author dell
 */
public class Accueil extends javax.swing.JFrame {
    /**
     * Creates new form Accueil
     */
            


  

    public Accueil() {
                            
        initComponents();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogoLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        AdminButton = new javax.swing.JLabel();
        ClientButton = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CloseLabel = new javax.swing.JLabel();
        RestaurateursButton1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(300, 50, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        LogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resto/gui/logo2big.gif"))); // NOI18N
        LogoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoLabelMouseClicked(evt);
            }
        });
        getContentPane().add(LogoLabel);
        LogoLabel.setBounds(200, 0, 420, 250);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resto/gui/jboss.gif"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(710, 500, 60, 60);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Created by");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(630, 530, 70, 14);

        AdminButton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AdminButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resto/gui/icon4.gif"))); // NOI18N
        AdminButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        AdminButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AdminButtonMouseEntered(evt);
            }
        });
        getContentPane().add(AdminButton);
        AdminButton.setBounds(110, 320, 140, 130);

        ClientButton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ClientButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resto/gui/icon6.gif"))); // NOI18N
        ClientButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ClientButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClientButtonMouseClicked(evt);
            }
        });
        getContentPane().add(ClientButton);
        ClientButton.setBounds(340, 320, 140, 130);

        jLabel6.setFont(new java.awt.Font("DK Early Morning Coffee", 3, 18));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Administateur");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(120, 290, 110, 24);

        jLabel8.setFont(new java.awt.Font("DK Early Morning Coffee", 3, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Client");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(350, 290, 110, 20);

        CloseLabel.setFont(new java.awt.Font("Century Gothic", 0, 11));
        CloseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CloseLabel.setText("[ X ]");
        CloseLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseLabelMouseClicked(evt);
            }
        });
        getContentPane().add(CloseLabel);
        CloseLabel.setBounds(770, 0, 30, 20);

        RestaurateursButton1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        RestaurateursButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resto/gui/icon7.gif"))); // NOI18N
        RestaurateursButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        RestaurateursButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RestaurateursButton1MouseClicked(evt);
            }
        });
        getContentPane().add(RestaurateursButton1);
        RestaurateursButton1.setBounds(560, 320, 144, 130);

        jLabel9.setFont(new java.awt.Font("DK Early Morning Coffee", 3, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Restaurateurs");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(570, 290, 110, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resto/gui/fondwood.jpg"))); // NOI18N
        jLabel1.setFocusable(false);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }//GEN-LAST:event_formWindowOpened

     
    private void LogoLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoLabelMouseClicked
           
        
    }//GEN-LAST:event_LogoLabelMouseClicked

    private void AdminButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminButtonMouseEntered
        
    }//GEN-LAST:event_AdminButtonMouseEntered

    private void AdminButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminButtonMouseClicked
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AuthentificationAdmin().setVisible(true);
                }
            
        });
         
    }//GEN-LAST:event_AdminButtonMouseClicked

    private void ClientButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientButtonMouseClicked
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AuthentificationClient().setVisible(true);
                }
            
        });
    }//GEN-LAST:event_ClientButtonMouseClicked

    private void CloseLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMouseClicked
        this.dispose();
    }//GEN-LAST:event_CloseLabelMouseClicked

    private void RestaurateursButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RestaurateursButton1MouseClicked
          java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AuthentificationRestaurateur().setVisible(true);
                }

        });
    }//GEN-LAST:event_RestaurateursButton1MouseClicked
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accueil().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminButton;
    private javax.swing.JLabel ClientButton;
    private javax.swing.JLabel CloseLabel;
    private javax.swing.JLabel LogoLabel;
    private javax.swing.JLabel RestaurateursButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
