/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package resto.gui;

/**
 *
 * @author dell
 */
public class AccueilAdmin extends javax.swing.JFrame {

    /**
     * Creates new form AccueilAdmin
     */
    public AccueilAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jGererClient = new javax.swing.JLabel();
        jGererRestaurateurs = new javax.swing.JLabel();
        jGererCommentaires = new javax.swing.JLabel();
        jModifierMonCompte = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        LogoLabel = new javax.swing.JLabel();
        CloseLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(300, 50, 0, 0));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jGererClient.setBackground(new java.awt.Color(148, 211, 58));
        jGererClient.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jGererClient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jGererClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resto/gui/icon4small.gif"))); // NOI18N
        jGererClient.setText("Gérer \nComptes Clients");
        jGererClient.setOpaque(true);
        jGererClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jGererClientMouseClicked(evt);
            }
        });
        getContentPane().add(jGererClient);
        jGererClient.setBounds(20, 30, 161, 60);

        jGererRestaurateurs.setBackground(new java.awt.Color(225, 50, 55));
        jGererRestaurateurs.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jGererRestaurateurs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jGererRestaurateurs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resto/gui/icon6small.gif"))); // NOI18N
        jGererRestaurateurs.setText("Gérer Comptes Restaurateurs");
        jGererRestaurateurs.setOpaque(true);
        jGererRestaurateurs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jGererRestaurateursMouseClicked(evt);
            }
        });
        getContentPane().add(jGererRestaurateurs);
        jGererRestaurateurs.setBounds(190, 30, 200, 60);

        jGererCommentaires.setBackground(new java.awt.Color(255, 127, 44));
        jGererCommentaires.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jGererCommentaires.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jGererCommentaires.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resto/gui/icon7small.gif"))); // NOI18N
        jGererCommentaires.setText("Gérer Les Commentaires");
        jGererCommentaires.setOpaque(true);
        jGererCommentaires.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jGererCommentairesMouseClicked(evt);
            }
        });
        getContentPane().add(jGererCommentaires);
        jGererCommentaires.setBounds(400, 30, 180, 60);

        jModifierMonCompte.setBackground(new java.awt.Color(172, 71, 173));
        jModifierMonCompte.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jModifierMonCompte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jModifierMonCompte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resto/gui/icon5small.gif"))); // NOI18N
        jModifierMonCompte.setText("Modifier Mon Compte");
        jModifierMonCompte.setOpaque(true);
        jModifierMonCompte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jModifierMonCompteMouseClicked(evt);
            }
        });
        getContentPane().add(jModifierMonCompte);
        jModifierMonCompte.setBounds(590, 30, 170, 60);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resto/gui/jboss.gif"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(710, 500, 60, 60);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Created by");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(630, 530, 70, 14);

        LogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resto/gui/logo2big.gif"))); // NOI18N
        LogoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoLabelMouseClicked(evt);
            }
        });
        getContentPane().add(LogoLabel);
        LogoLabel.setBounds(200, 160, 400, 260);

        CloseLabel.setFont(new java.awt.Font("Century Gothic", 0, 11));
        CloseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CloseLabel.setText("[ X ]");
        CloseLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseLabelMouseClicked(evt);
            }
        });
        getContentPane().add(CloseLabel);
        CloseLabel.setBounds(770, 0, 30, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resto/gui/fondwood.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoLabelMouseClicked

    }//GEN-LAST:event_LogoLabelMouseClicked

    private void CloseLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMouseClicked
        this.dispose();
    }//GEN-LAST:event_CloseLabelMouseClicked

    private void jGererClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jGererClientMouseClicked
           java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GererComptesClients().setVisible(true);
                }

        });
         this.dispose();
    
    }//GEN-LAST:event_jGererClientMouseClicked

    private void jGererRestaurateursMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jGererRestaurateursMouseClicked
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GererRestaurateurs().setVisible(true);
                }

        });
         this.dispose();
    }//GEN-LAST:event_jGererRestaurateursMouseClicked

    private void jGererCommentairesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jGererCommentairesMouseClicked
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GererCommentaires().setVisible(true);
                }

        });
         this.dispose();
    }//GEN-LAST:event_jGererCommentairesMouseClicked

    private void jModifierMonCompteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jModifierMonCompteMouseClicked
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateAdmin().setVisible(true);
                }

        });
         this.dispose();
    }//GEN-LAST:event_jModifierMonCompteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccueilAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccueilAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccueilAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccueilAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccueilAdmin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CloseLabel;
    private javax.swing.JLabel LogoLabel;
    private javax.swing.JLabel jGererClient;
    private javax.swing.JLabel jGererCommentaires;
    private javax.swing.JLabel jGererRestaurateurs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jModifierMonCompte;
    // End of variables declaration//GEN-END:variables
}
