/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package resto.gui;

import javax.swing.JOptionPane;
import resto.DAO.*;
import resto.entities.Restaurant;

/**
 *
 * @author dell
 */
public class AjoutRestaurant extends javax.swing.JFrame {

    /**
     * Creates new form AjoutRestaurant
     */
    public AjoutRestaurant() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogoLabel = new javax.swing.JLabel();
        CloseLabel = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jres = new javax.swing.JTextField();
        alcool = new javax.swing.JComboBox();
        region = new javax.swing.JComboBox();
        ambiance = new javax.swing.JComboBox();
        budget = new javax.swing.JComboBox();
        spec = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        table = new javax.swing.JSpinner();
        ajouter = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        AjouterClientLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(300, 50, 0, 0));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setUndecorated(true);
        getContentPane().setLayout(null);

        LogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resto/gui/logo2.gif"))); // NOI18N
        LogoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoLabelMouseClicked(evt);
            }
        });
        getContentPane().add(LogoLabel);
        LogoLabel.setBounds(560, 0, 200, 150);

        CloseLabel.setFont(new java.awt.Font("Century Gothic", 0, 11));
        CloseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CloseLabel.setText("[ X ]");
        CloseLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseLabelMouseClicked(evt);
            }
        });
        getContentPane().add(CloseLabel);
        CloseLabel.setBounds(770, 0, 30, 20);

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 14));
        jLabel21.setText("<html>Veuillez remplir vos données pour ajouter votre Restaurant</html>");
        jLabel21.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel21);
        jLabel21.setBounds(70, 170, 510, 30);

        jres.setText("Entrez le nom de votre restaurant");
        getContentPane().add(jres);
        jres.setBounds(210, 230, 160, 30);

        alcool.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Avec", "Sans" }));
        alcool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alcoolActionPerformed(evt);
            }
        });
        getContentPane().add(alcool);
        alcool.setBounds(550, 350, 160, 30);

        region.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tunis", "Sousse", "Bizerte", "Nabeul", "Sfax", "Mahdia", "Djerba" }));
        region.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regionActionPerformed(evt);
            }
        });
        getContentPane().add(region);
        region.setBounds(210, 290, 160, 30);

        ambiance.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Romantique", "Branché", "Business", "Karaoké", "Familale" }));
        ambiance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ambianceActionPerformed(evt);
            }
        });
        getContentPane().add(ambiance);
        ambiance.setBounds(550, 220, 160, 30);

        budget.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "15dt - 30dt", "30dt - 40dt", "40dt - 60dt", "60dt +", "" }));
        budget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                budgetActionPerformed(evt);
            }
        });
        getContentPane().add(budget);
        budget.setBounds(550, 270, 160, 30);

        spec.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tunisienne", "Marocaine", "Italienne", "Japonnaise", "Idienne", "Libanaise" }));
        spec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specActionPerformed(evt);
            }
        });
        getContentPane().add(spec);
        spec.setBounds(210, 350, 160, 30);

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel16.setText("Nombre tables*");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(440, 310, 100, 20);

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel15.setText("Alcool *");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(450, 350, 60, 20);

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel14.setText("Spécialité *");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(80, 350, 90, 20);

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel11.setText("Région*");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(80, 290, 110, 20);

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel9.setText("Nom Restaurant*");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(80, 230, 120, 20);

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel12.setText("Budget Moyen*");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(440, 270, 110, 20);

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel13.setText("Ambiance*");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(440, 230, 80, 14);

        jLabel24.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel24.setText("Les champs marqués d'un * sont obligatoires. ");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(70, 410, 300, 14);
        getContentPane().add(table);
        table.setBounds(550, 310, 160, 20);

        ajouter.setText("Ajouter");
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });
        getContentPane().add(ajouter);
        ajouter.setBounds(190, 450, 110, 23);

        jButton1.setText("Retour");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(550, 450, 110, 23);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Created by");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(630, 530, 70, 14);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resto/gui/jboss.gif"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(710, 500, 60, 60);

        AjouterClientLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ajouter un Restaurant", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 11))); // NOI18N
        getContentPane().add(AjouterClientLabel);
        AjouterClientLabel.setBounds(50, 140, 700, 350);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 24));
        jLabel7.setText("Ajouter un Restaurant");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 60, 350, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resto/gui/fondwood.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(800, 600));
        jLabel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jLabel1.setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoLabelMouseClicked

    }//GEN-LAST:event_LogoLabelMouseClicked

    private void CloseLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMouseClicked
        this.dispose();
    }//GEN-LAST:event_CloseLabelMouseClicked

    private void alcoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alcoolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alcoolActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccueilRestaurateur().setVisible(true);
            }
        });
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void regionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regionActionPerformed

    private void budgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_budgetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_budgetActionPerformed

    private void ambianceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ambianceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ambianceActionPerformed

    private void specActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_specActionPerformed

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed

        Restaurant restaurant = new Restaurant();
        RestaurantDAO restaurantDAO= new RestaurantDAO();
        restaurateurDAO RestaurateurDAO = new restaurateurDAO();
        int nbtable = Integer.parseInt(table.getValue().toString());

        restaurant.setBudget_moy(budget.getSelectedItem().toString());
        restaurant.setRegion(region.getSelectedItem().toString());
        restaurant.setNom_restaurant(jres.getText());
        restaurant.setNbre_table(nbtable);
        restaurant.setAmbiance(ambiance.getSelectedItem().toString());
        restaurant.setAlcool(alcool.getSelectedItem().toString());
        restaurant.setSpecialite(spec.getSelectedItem().toString());
        restaurant.setId_restaurateur(RestaurateurDAO.getId(Integer.MAX_VALUE));
        restaurantDAO.insertRestaurant(restaurant);
        JOptionPane.showMessageDialog(this,"Ajout du restaurant est effectué avec succès");



        // TODO add your handling code here:
    }//GEN-LAST:event_ajouterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjoutRestaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjoutRestaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjoutRestaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjoutRestaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjoutRestaurant().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AjouterClientLabel;
    private javax.swing.JLabel CloseLabel;
    private javax.swing.JLabel LogoLabel;
    private javax.swing.JButton ajouter;
    private javax.swing.JComboBox alcool;
    private javax.swing.JComboBox ambiance;
    private javax.swing.JComboBox budget;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jres;
    private javax.swing.JComboBox region;
    private javax.swing.JComboBox spec;
    private javax.swing.JSpinner table;
    // End of variables declaration//GEN-END:variables
}
