/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package resto.gui;

import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import resto.util.MyConnection;

/**
 *
 * @author dell
 */
public class AuthentificationAdmin extends javax.swing.JFrame {

    /**
     * Creates new form AuthentificationAdmin
     */
    public AuthentificationAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelAuthentification = new javax.swing.JLabel();
        LabelPwd = new javax.swing.JLabel();
        LabelLogin = new javax.swing.JLabel();
        jlogin = new javax.swing.JTextField();
        jpwd = new javax.swing.JPasswordField();
        AnnulerButton = new javax.swing.JButton();
        ConnexionButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(500, 150, 0, 0));
        setMinimumSize(new java.awt.Dimension(400, 400));
        setName("Authentification"); // NOI18N
        setResizable(false);
        setUndecorated(true);
        getContentPane().setLayout(null);

        LabelAuthentification.setFont(new java.awt.Font("DK Early Morning Coffee", 1, 36));
        LabelAuthentification.setForeground(new java.awt.Color(255, 255, 255));
        LabelAuthentification.setText("Authentification");
        getContentPane().add(LabelAuthentification);
        LabelAuthentification.setBounds(80, 20, 250, 50);

        LabelPwd.setFont(new java.awt.Font("Century Gothic", 1, 14));
        LabelPwd.setForeground(new java.awt.Color(255, 255, 255));
        LabelPwd.setText("Password :");
        getContentPane().add(LabelPwd);
        LabelPwd.setBounds(50, 180, 80, 19);

        LabelLogin.setFont(new java.awt.Font("Century Gothic", 1, 14));
        LabelLogin.setForeground(new java.awt.Color(255, 255, 255));
        LabelLogin.setText("Login :");
        getContentPane().add(LabelLogin);
        LabelLogin.setBounds(50, 130, 50, 19);

        jlogin.setText("Entrez votre login");
        jlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jloginMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jloginMouseReleased(evt);
            }
        });
        getContentPane().add(jlogin);
        jlogin.setBounds(160, 130, 170, 20);

        jpwd.setText("jPasswordField1");
        jpwd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpwdMouseClicked(evt);
            }
        });
        getContentPane().add(jpwd);
        jpwd.setBounds(160, 180, 170, 20);

        AnnulerButton.setText("Annuler");
        AnnulerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AnnulerButton);
        AnnulerButton.setBounds(140, 280, 110, 23);

        ConnexionButton1.setText("Connexion");
        ConnexionButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConnexionButton1MouseClicked(evt);
            }
        });
        ConnexionButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConnexionButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(ConnexionButton1);
        ConnexionButton1.setBounds(140, 240, 110, 23);

        jLabel1.setBackground(new java.awt.Color(148, 211, 58));
        jLabel1.setForeground(new java.awt.Color(148, 211, 58));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setMaximumSize(new java.awt.Dimension(400, 400));
        jLabel1.setMinimumSize(new java.awt.Dimension(400, 400));
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(400, 400));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AnnulerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_AnnulerButtonActionPerformed

    private void jloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jloginMouseClicked
        jlogin.setText("");
    }//GEN-LAST:event_jloginMouseClicked

    private void jpwdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpwdMouseClicked
        jpwd.setText("");
    }//GEN-LAST:event_jpwdMouseClicked
                          
    private void jloginMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jloginMouseReleased
        
    }//GEN-LAST:event_jloginMouseReleased

    private void ConnexionButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConnexionButton1ActionPerformed
        String requete = "SELECT * FROM administrateur";

        try {
            Statement statement = MyConnection.getInstance().createStatement();
            ResultSet resultat = statement.executeQuery(requete);

            while (resultat.next()) {
                char[] pwd1 = jpwd.getPassword();
                String pwd2 = new String(pwd1);


                if ((jlogin.getText().equals(resultat.getString(2))) && (pwd2.equals(resultat.getString(3)))) {
                    java.awt.EventQueue.invokeLater(new Runnable() {

                        public void run() {
                            new AccueilAdmin().setVisible(true);
                        }
                    });
                    this.dispose();

                   
                } else {
                    JOptionPane.showMessageDialog(this, "Login ou mot de passe invalide ! Réessayez");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Probème de connexion");

            
        }        
    }//GEN-LAST:event_ConnexionButton1ActionPerformed

    private void ConnexionButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConnexionButton1MouseClicked
        {
        String requete = "SELECT * FROM administrateur";

        try {
            Statement statement = MyConnection.getInstance().createStatement();
            ResultSet resultat = statement.executeQuery(requete);

            while (resultat.next()) {
                char[] pwd1 = jpwd.getPassword();
                String pwd2 = new String(pwd1);


                if ((jlogin.getText().equals(resultat.getString(2))) && (pwd2.equals(resultat.getString(3)))) {
                    java.awt.EventQueue.invokeLater(new Runnable() {

                        public void run() {
                            new AccueilAdmin().setVisible(true);
                        }
                    });
                    this.dispose();

                    // JOptionPane.showMessageDialog(this, "Connecté");
                } else {
                    JOptionPane.showMessageDialog(this, "Login ou mot de passe invalide ! Réessayez");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Probème de connexion");

            //System.out.println("echec pilote : " + e);
        }        // TODO add your handling code here:

    }//GEN-LAST:event_ConnexionButton1MouseClicked
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuthentificationAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuthentificationAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuthentificationAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuthentificationAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AuthentificationAdmin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnnulerButton;
    private javax.swing.JButton ConnexionButton1;
    private javax.swing.JLabel LabelAuthentification;
    private javax.swing.JLabel LabelLogin;
    private javax.swing.JLabel LabelPwd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jlogin;
    private javax.swing.JPasswordField jpwd;
    // End of variables declaration//GEN-END:variables
}
