/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package resto.gui;
import java.sql.*;
import javax.swing.JOptionPane;
import resto.util.MyConnection;
/**
 *
 * @author dell
 */
public class AuthentificationRestaurateur extends javax.swing.JFrame {

    /**
     * Creates new form AuthentificationClient
     */
    public AuthentificationRestaurateur() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelAuthentification = new javax.swing.JLabel();
        LabelLogin = new javax.swing.JLabel();
        jlogin = new javax.swing.JTextField();
        jpwd = new javax.swing.JPasswordField();
        LabelPwd = new javax.swing.JLabel();
        AnnulerButton2 = new javax.swing.JButton();
        InscrireButton = new javax.swing.JButton();
        ConnexionButton = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(500, 150, 0, 0));
        setMaximizedBounds(new java.awt.Rectangle(500, 150, 0, 0));
        setMinimumSize(new java.awt.Dimension(400, 400));
        setName("AuthentificationClient"); // NOI18N
        setResizable(false);
        setUndecorated(true);
        getContentPane().setLayout(null);

        LabelAuthentification.setFont(new java.awt.Font("DK Early Morning Coffee", 1, 36));
        LabelAuthentification.setForeground(new java.awt.Color(255, 255, 255));
        LabelAuthentification.setText("Authentification");
        getContentPane().add(LabelAuthentification);
        LabelAuthentification.setBounds(80, 20, 250, 50);

        LabelLogin.setFont(new java.awt.Font("Century Gothic", 1, 14));
        LabelLogin.setForeground(new java.awt.Color(255, 255, 255));
        LabelLogin.setText("Login :");
        getContentPane().add(LabelLogin);
        LabelLogin.setBounds(50, 130, 50, 19);

        jlogin.setText("Entrez votre login");
        jlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jloginMouseClicked(evt);
            }
        });
        getContentPane().add(jlogin);
        jlogin.setBounds(160, 130, 170, 20);

        jpwd.setText("jPasswordField1");
        jpwd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpwdMouseClicked(evt);
            }
        });
        getContentPane().add(jpwd);
        jpwd.setBounds(160, 180, 170, 20);

        LabelPwd.setFont(new java.awt.Font("Century Gothic", 1, 14));
        LabelPwd.setForeground(new java.awt.Color(255, 255, 255));
        LabelPwd.setText("Password :");
        getContentPane().add(LabelPwd);
        LabelPwd.setBounds(50, 180, 80, 19);

        AnnulerButton2.setText("Annuler");
        AnnulerButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AnnulerButton2MouseClicked(evt);
            }
        });
        AnnulerButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(AnnulerButton2);
        AnnulerButton2.setBounds(150, 310, 110, 23);

        InscrireButton.setText("S'inscrire");
        InscrireButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InscrireButtonMouseClicked(evt);
            }
        });
        InscrireButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InscrireButtonActionPerformed(evt);
            }
        });
        getContentPane().add(InscrireButton);
        InscrireButton.setBounds(150, 270, 110, 23);

        ConnexionButton.setText("Connexion");
        ConnexionButton.setActionCommand("Connexion");
        ConnexionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConnexionButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ConnexionButton);
        ConnexionButton.setBounds(150, 230, 110, 23);

        jLabel1.setBackground(new java.awt.Color(225, 127, 44));
        jLabel1.setMaximumSize(new java.awt.Dimension(400, 400));
        jLabel1.setMinimumSize(new java.awt.Dimension(400, 400));
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(400, 400));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InscrireButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InscrireButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InscrireButtonActionPerformed

    private void AnnulerButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_AnnulerButton2ActionPerformed

    private void AnnulerButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnnulerButton2MouseClicked
        this.dispose();
    }//GEN-LAST:event_AnnulerButton2MouseClicked

    private void jloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jloginMouseClicked
        jlogin.setText("");
    }//GEN-LAST:event_jloginMouseClicked

    private void jpwdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpwdMouseClicked
        jpwd.setText("");
    }//GEN-LAST:event_jpwdMouseClicked

    private void InscrireButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InscrireButtonMouseClicked
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InscriptionRestaurateur().setVisible(true);
                }

        });
        this.dispose();
    }//GEN-LAST:event_InscrireButtonMouseClicked

    private void ConnexionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConnexionButtonActionPerformed
         String requete = "SELECT * FROM restaurateur";

        try {
            Statement statement = MyConnection.getInstance().createStatement();
            ResultSet resultat = statement.executeQuery(requete);

            while (resultat.next()) {
                char[] pwd1 = jpwd.getPassword();
                String pwd2 = new String(pwd1);


                if ((jlogin.getText().equals(resultat.getString(6))) && (pwd2.equals(resultat.getString(7)))) {
                    java.awt.EventQueue.invokeLater(new Runnable() {

                        public void run() {
                            new AccueilRestaurateur().setVisible(true);
                        }
                    });
                    this.dispose();


                } 
                else {
                    JOptionPane.showMessageDialog(this, "Login ou mot de passe invalide ! Réessayez");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Probème de connexion");


        }
    }//GEN-LAST:event_ConnexionButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuthentificationRestaurateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuthentificationRestaurateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuthentificationRestaurateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuthentificationRestaurateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AuthentificationRestaurateur().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnnulerButton2;
    private javax.swing.JToggleButton ConnexionButton;
    private javax.swing.JButton InscrireButton;
    private javax.swing.JLabel LabelAuthentification;
    private javax.swing.JLabel LabelLogin;
    private javax.swing.JLabel LabelPwd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jlogin;
    private javax.swing.JPasswordField jpwd;
    // End of variables declaration//GEN-END:variables
}
