/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package resto.gui;

import resto.DAO.restaurateurDAO;
import resto.entities.Restaurant;
import resto.entities.restaurateur;

/**
 *
 * @author dell
 */
public class GererRestaurateurs extends javax.swing.JFrame {

    /**
     * Creates new form GererRestaurateurs
     */
    public GererRestaurateurs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jGererClient = new javax.swing.JLabel();
        jGererRestaurateurs = new javax.swing.JLabel();
        jGererCommentaires = new javax.swing.JLabel();
        jModifierMonCompte = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jnom = new javax.swing.JTextField();
        jnomres = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        AjouterClientLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CloseLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(300, 50, 0, 0));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jGererClient.setBackground(new java.awt.Color(148, 211, 58));
        jGererClient.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jGererClient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jGererClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resto/gui/icon4small.gif"))); // NOI18N
        jGererClient.setText("Gérer \nComptes Clients");
        jGererClient.setOpaque(true);
        jGererClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jGererClientMouseClicked(evt);
            }
        });
        getContentPane().add(jGererClient);
        jGererClient.setBounds(20, 30, 161, 60);

        jGererRestaurateurs.setBackground(new java.awt.Color(225, 50, 55));
        jGererRestaurateurs.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jGererRestaurateurs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jGererRestaurateurs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resto/gui/icon6small.gif"))); // NOI18N
        jGererRestaurateurs.setText("Gérer Comptes Restaurateurs");
        jGererRestaurateurs.setOpaque(true);
        getContentPane().add(jGererRestaurateurs);
        jGererRestaurateurs.setBounds(190, 30, 200, 60);

        jGererCommentaires.setBackground(new java.awt.Color(255, 127, 44));
        jGererCommentaires.setFont(new java.awt.Font("Century Gothic", 1, 10));
        jGererCommentaires.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jGererCommentaires.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resto/gui/icon7small.gif"))); // NOI18N
        jGererCommentaires.setText("Gérer Les Commentaires");
        jGererCommentaires.setOpaque(true);
        jGererCommentaires.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jGererCommentairesMouseClicked(evt);
            }
        });
        getContentPane().add(jGererCommentaires);
        jGererCommentaires.setBounds(400, 30, 180, 60);

        jModifierMonCompte.setBackground(new java.awt.Color(172, 71, 173));
        jModifierMonCompte.setFont(new java.awt.Font("Century Gothic", 1, 10));
        jModifierMonCompte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jModifierMonCompte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resto/gui/icon5small.gif"))); // NOI18N
        jModifierMonCompte.setText("Modifier Mon Compte");
        jModifierMonCompte.setOpaque(true);
        jModifierMonCompte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jModifierMonCompteMouseClicked(evt);
            }
        });
        getContentPane().add(jModifierMonCompte);
        jModifierMonCompte.setBounds(590, 30, 170, 60);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Gérer Les Comptes Restaurateurs");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 110, 280, 19);

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel17.setText("<html>Veuillez saisir au minimum un champ afin de trouver un restaurateur</html>");
        jLabel17.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel17);
        jLabel17.setBounds(70, 170, 510, 30);

        jnom.setText("Entrez un nom restaurateur");
        getContentPane().add(jnom);
        jnom.setBounds(240, 220, 160, 30);

        jnomres.setText("Entrez un nom restaurant");
        jnomres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnomresActionPerformed(evt);
            }
        });
        getContentPane().add(jnomres);
        jnomres.setBounds(240, 270, 160, 30);

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jLabel11.setText("Les champs marqués d'un * sont obligatoires.\n");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(70, 320, 300, 14);

        jButton2.setText("Trouver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(260, 360, 90, 23);

        jButton1.setText("Annuler");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(370, 360, 90, 23);

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel10.setText("Nom restaurant  *");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(100, 280, 120, 14);

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel9.setText("Nom restaurateur *");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(100, 230, 120, 16);

        AjouterClientLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Recherche un Restaurateurs", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 11))); // NOI18N
        getContentPane().add(AjouterClientLabel);
        AjouterClientLabel.setBounds(50, 140, 640, 320);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Created by");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(630, 530, 70, 14);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resto/gui/jboss.gif"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(710, 500, 60, 60);

        CloseLabel.setFont(new java.awt.Font("Century Gothic", 0, 11));
        CloseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CloseLabel.setText("[ X ]");
        CloseLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseLabelMouseClicked(evt);
            }
        });
        getContentPane().add(CloseLabel);
        CloseLabel.setBounds(770, 0, 30, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resto/gui/fondwood.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CloseLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMouseClicked
        this.dispose();
    }//GEN-LAST:event_CloseLabelMouseClicked

    private void jGererClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jGererClientMouseClicked
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GererComptesClients().setVisible(true);
                }

        });
         this.dispose();
    }//GEN-LAST:event_jGererClientMouseClicked

    private void jGererCommentairesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jGererCommentairesMouseClicked
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GererCommentaires().setVisible(true);
                }

        });
         this.dispose();
    }//GEN-LAST:event_jGererCommentairesMouseClicked

    private void jModifierMonCompteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jModifierMonCompteMouseClicked
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateAdmin().setVisible(true);
                }

        });
         this.dispose();
    }//GEN-LAST:event_jModifierMonCompteMouseClicked

    private void jnomresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnomresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnomresActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
restaurateur rest = new restaurateur();
restaurateurDAO rstdao= new restaurateurDAO();
Restaurant restaurant = new Restaurant();


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GererRestaurateurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GererRestaurateurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GererRestaurateurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GererRestaurateurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GererRestaurateurs().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AjouterClientLabel;
    private javax.swing.JLabel CloseLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jGererClient;
    private javax.swing.JLabel jGererCommentaires;
    private javax.swing.JLabel jGererRestaurateurs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jModifierMonCompte;
    private javax.swing.JTextField jnom;
    private javax.swing.JTextField jnomres;
    // End of variables declaration//GEN-END:variables
}
