/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package resto.gui;

import javax.swing.JOptionPane;
import resto.DAO.restaurateurDAO;
import resto.entities.restaurateur;

/**
 *
 * @author dell
 */
public class InscriptionRestaurateur extends javax.swing.JFrame {

    /**
     * Creates new form InscriptionClient
     */
    public InscriptionRestaurateur() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogoLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jnom = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jemail = new javax.swing.JTextField();
        jtel = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jlogin = new javax.swing.JTextField();
        jpwd = new javax.swing.JPasswordField();
        cpwd = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        inscrire = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jprenom = new javax.swing.JTextField();
        AjouterClientLabel = new javax.swing.JLabel();
        CloseLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(300, 50, 0, 0));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setUndecorated(true);
        getContentPane().setLayout(null);

        LogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resto/gui/logo2.gif"))); // NOI18N
        LogoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoLabelMouseClicked(evt);
            }
        });
        getContentPane().add(LogoLabel);
        LogoLabel.setBounds(560, 0, 200, 150);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resto/gui/jboss.gif"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(710, 500, 60, 60);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Created by");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(630, 530, 70, 14);

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel9.setText("Nom: *");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(90, 230, 40, 16);

        jnom.setText("Entrer votre Nom");
        jnom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jnomMouseClicked(evt);
            }
        });
        getContentPane().add(jnom);
        jnom.setBounds(170, 220, 160, 30);

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel11.setText("Prénom: *");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(90, 270, 60, 14);

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel12.setText("Email: *");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(90, 310, 60, 20);

        jemail.setText("flenbenfoulen@mail.com");
        jemail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jemailMouseClicked(evt);
            }
        });
        getContentPane().add(jemail);
        jemail.setBounds(170, 310, 160, 30);

        jtel.setText("Entrer votre Num de Tél");
        jtel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtelMouseClicked(evt);
            }
        });
        getContentPane().add(jtel);
        jtel.setBounds(170, 350, 160, 30);

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel13.setText("Tél: *");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(90, 350, 60, 20);

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel15.setText("Login: *");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(430, 240, 60, 20);

        jlogin.setText("Choisir un Login");
        jlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jloginMouseClicked(evt);
            }
        });
        jlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jloginActionPerformed(evt);
            }
        });
        getContentPane().add(jlogin);
        jlogin.setBounds(570, 230, 160, 30);

        jpwd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpwdMouseClicked(evt);
            }
        });
        getContentPane().add(jpwd);
        jpwd.setBounds(570, 280, 160, 30);

        cpwd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cpwdMouseClicked(evt);
            }
        });
        getContentPane().add(cpwd);
        cpwd.setBounds(570, 330, 160, 30);

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel16.setText("Password  *");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(430, 290, 80, 20);

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel17.setText("<html>Confirmer password  *</html>");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(430, 330, 130, 40);

        jButton1.setText("Annuler");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(550, 450, 110, 23);

        inscrire.setText("S'inscrire");
        inscrire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscrireActionPerformed(evt);
            }
        });
        getContentPane().add(inscrire);
        inscrire.setBounds(190, 450, 110, 23);

        jLabel21.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel21.setText("<html>Veuillez remplir vos données pour vous inscrire.</html>");
        jLabel21.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel21);
        jLabel21.setBounds(70, 170, 510, 30);

        jLabel24.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel24.setText("Les champs marqués d'un * sont obligatoires.\n");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(70, 410, 300, 16);

        jprenom.setText("Entrer votre Prénom");
        jprenom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jprenomMouseClicked(evt);
            }
        });
        jprenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jprenomActionPerformed(evt);
            }
        });
        getContentPane().add(jprenom);
        jprenom.setBounds(170, 265, 160, 30);

        AjouterClientLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inscription Restaurateurs", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 11))); // NOI18N
        getContentPane().add(AjouterClientLabel);
        AjouterClientLabel.setBounds(50, 140, 700, 350);

        CloseLabel.setFont(new java.awt.Font("Century Gothic", 0, 11));
        CloseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CloseLabel.setText("[ X ]");
        CloseLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseLabelMouseClicked(evt);
            }
        });
        getContentPane().add(CloseLabel);
        CloseLabel.setBounds(770, 0, 30, 20);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 24));
        jLabel7.setText("Inscription Restaurateurs");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 49, 360, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resto/gui/fondwood.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoLabelMouseClicked
    }//GEN-LAST:event_LogoLabelMouseClicked

    private void jloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jloginActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CloseLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMouseClicked
        this.dispose();
    }//GEN-LAST:event_CloseLabelMouseClicked

    private void inscrireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscrireActionPerformed
        restaurateurDAO rdao = new restaurateurDAO();
        restaurateur res = new restaurateur();

        char[] pwd1 = jpwd.getPassword();
        String pwd2 = new String(pwd1);

        char[] pwd12 = cpwd.getPassword();
        String pwd22 = new String(pwd1);

        int tel = new Integer(jtel.getText());
        res.setNom(jnom.getText());
        res.setPrenom(jprenom.getText());
        res.setEmail(jemail.getText());
        res.setNom(jnom.getText());
        res.setTel(tel);
        res.setLogin(jlogin.getText());

        if (pwd2.equals(pwd22)) {
            res.setPwd(pwd22);
        }


        rdao.insertrestaurateur(res);
        JOptionPane.showMessageDialog(this, "Vous êtes inscrit");

        // TODO add your handling code here:
    }//GEN-LAST:event_inscrireActionPerformed

    private void jnomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jnomMouseClicked
jnom.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jnomMouseClicked

    private void jprenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jprenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jprenomActionPerformed

    private void jprenomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jprenomMouseClicked
jprenom.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jprenomMouseClicked

    private void jemailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jemailMouseClicked
jemail.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jemailMouseClicked

    private void jtelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtelMouseClicked
jtel.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jtelMouseClicked

    private void jloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jloginMouseClicked
jlogin.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jloginMouseClicked

    private void jpwdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpwdMouseClicked
jpwd.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jpwdMouseClicked

    private void cpwdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cpwdMouseClicked
cpwd.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_cpwdMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InscriptionClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InscriptionClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InscriptionClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InscriptionClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new InscriptionRestaurateur().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AjouterClientLabel;
    private javax.swing.JLabel CloseLabel;
    private javax.swing.JLabel LogoLabel;
    private javax.swing.JPasswordField cpwd;
    private javax.swing.JButton inscrire;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jemail;
    private javax.swing.JTextField jlogin;
    private javax.swing.JTextField jnom;
    private javax.swing.JTextField jprenom;
    private javax.swing.JPasswordField jpwd;
    private javax.swing.JTextField jtel;
    // End of variables declaration//GEN-END:variables
}
