/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package resto.gui;

/**
 *
 * @author dell
 */
public class InscriptionClient extends javax.swing.JFrame {

    /**
     * Creates new form InscriptionClient
     */
    public InscriptionClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogoLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        AjouterClientLabel = new javax.swing.JLabel();
        CloseLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(300, 50, 0, 0));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setUndecorated(true);
        getContentPane().setLayout(null);

        LogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resto/gui/logo2.gif"))); // NOI18N
        LogoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoLabelMouseClicked(evt);
            }
        });
        getContentPane().add(LogoLabel);
        LogoLabel.setBounds(560, 0, 200, 150);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resto/gui/jboss.gif"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(710, 500, 60, 60);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Created by");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(630, 530, 70, 14);

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 12));
        jLabel9.setText("Nom: *");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(90, 230, 40, 16);

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 12));
        jLabel10.setText("Sexe: ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(90, 310, 60, 14);

        jTextField3.setForeground(new java.awt.Color(204, 204, 204));
        jTextField3.setText("Entrer votre Nom");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(170, 225, 160, 20);

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 12));
        jLabel11.setText("Prénom: *");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(90, 270, 60, 14);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Homme", "Femme" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(170, 305, 160, 20);

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 12));
        jLabel12.setText("Email: *");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(90, 350, 60, 14);

        jTextField4.setForeground(new java.awt.Color(204, 204, 204));
        jTextField4.setText("flenbenfoulen@mail.com");
        getContentPane().add(jTextField4);
        jTextField4.setBounds(170, 345, 160, 20);

        jTextField5.setForeground(new java.awt.Color(204, 204, 204));
        jTextField5.setText("Entrer votre Num de Tél");
        getContentPane().add(jTextField5);
        jTextField5.setBounds(170, 385, 160, 20);

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 12));
        jLabel13.setText("Tél: *");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(90, 390, 60, 14);

        jTextField6.setForeground(new java.awt.Color(204, 204, 204));
        jTextField6.setText("Entrer votre Adresse");
        getContentPane().add(jTextField6);
        jTextField6.setBounds(530, 227, 160, 20);

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 12));
        jLabel14.setText("Adresse: *");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(450, 230, 60, 16);

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 12));
        jLabel15.setText("Login: *");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(450, 270, 60, 16);

        jTextField7.setForeground(new java.awt.Color(204, 204, 204));
        jTextField7.setText("Choisir un Login");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7);
        jTextField7.setBounds(530, 268, 160, 20);

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 12));
        jLabel16.setText("Pwd: *");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(450, 310, 60, 16);

        jTextField8.setForeground(new java.awt.Color(204, 204, 204));
        jTextField8.setText("Entrer votre mot de passe");
        getContentPane().add(jTextField8);
        jTextField8.setBounds(530, 308, 160, 20);

        jTextField9.setForeground(new java.awt.Color(204, 204, 204));
        jTextField9.setText("Confirmer votre mot de passe");
        getContentPane().add(jTextField9);
        jTextField9.setBounds(530, 350, 160, 20);

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 12));
        jLabel17.setText("<html>Confirmer Pwd: *</html>");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(450, 350, 80, 30);

        jButton1.setText("Annuler");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(550, 450, 110, 23);

        jButton2.setText("S'inscrire");
        getContentPane().add(jButton2);
        jButton2.setBounds(190, 450, 110, 23);

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 14));
        jLabel21.setText("<html>Veuillez remplir vos données pour vous inscrire.</html>");
        jLabel21.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel21);
        jLabel21.setBounds(70, 170, 510, 30);

        jLabel24.setFont(new java.awt.Font("Century Gothic", 0, 10));
        jLabel24.setText("Les champs marqués d'un * sont obligatoires.\n");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(70, 420, 300, 14);

        jTextField10.setForeground(new java.awt.Color(204, 204, 204));
        jTextField10.setText("Entrer votre Prénom");
        getContentPane().add(jTextField10);
        jTextField10.setBounds(170, 265, 160, 20);

        AjouterClientLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inscription Client", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 11))); // NOI18N
        getContentPane().add(AjouterClientLabel);
        AjouterClientLabel.setBounds(50, 140, 700, 350);

        CloseLabel.setFont(new java.awt.Font("Century Gothic", 0, 11));
        CloseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CloseLabel.setText("[ X ]");
        CloseLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseLabelMouseClicked(evt);
            }
        });
        getContentPane().add(CloseLabel);
        CloseLabel.setBounds(770, 0, 30, 20);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 24));
        jLabel7.setText("Inscription Client");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 49, 360, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resto/gui/fondwood.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoLabelMouseClicked

    }//GEN-LAST:event_LogoLabelMouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CloseLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMouseClicked
        this.dispose();
    }//GEN-LAST:event_CloseLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InscriptionClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InscriptionClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InscriptionClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InscriptionClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InscriptionClient().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AjouterClientLabel;
    private javax.swing.JLabel CloseLabel;
    private javax.swing.JLabel LogoLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
